export interface CommandDef {
  name: string;
  desc: string;
  argHint?: string;
}

export const COMMANDS: CommandDef[] = [
  { name: '/help',      desc: 'Show available commands' },
  { name: '/reset',     desc: 'Clear conversation' },
  { name: '/compact',   desc: 'Compact context' },
  { name: '/refresh',   desc: 'Reload workspace files' },
  { name: '/restart',   desc: 'Restart server' },
  { name: '/reload',    desc: 'Typecheck → build → restart server' },
  { name: '/reasoning', desc: 'Toggle reasoning',          argHint: 'on|off' },
  { name: '/effort',    desc: 'Set effort level',          argHint: 'low|medium|high|max' },
  { name: '/short',     desc: 'Short/voice mode',            argHint: 'on|off' },
  { name: '/model',     desc: 'Show or switch model',      argHint: '<name>' },
  { name: '/image',     desc: 'Send an image',             argHint: '<path> [msg]' },
  { name: '/usage',     desc: 'Token usage stats' },
  { name: '/context',   desc: 'Context window breakdown' },
  { name: '/tasks',     desc: 'Background tasks' },
  { name: '/profiles',  desc: 'List profiles' },
  { name: '/profile',   desc: 'Switch profile',            argHint: '<name>' },
  { name: '/save',      desc: 'Save session' },
  { name: '/sessions',  desc: 'List sessions' },
  { name: '/load',      desc: 'Load session',              argHint: '<id>' },
  { name: '/grant',     desc: 'Approve pending request' },
  { name: '/deny',      desc: 'Deny pending request' },
  { name: '/approve',        desc: 'Approve config write' },
  { name: '/reject',         desc: 'Reject config write' },
  { name: '/preview',        desc: 'Preview config write' },
  { name: '/approve-patch',  desc: 'Approve patch request' },
  { name: '/reject-patch',   desc: 'Reject patch request' },
];

export type SettingType = 'toggle' | 'slider' | 'number' | 'text' | 'select' | 'password' | 'string-list' | 'model-picker' | 'model-tokens';

export interface SettingDef {
  key: string;
  label: string;
  desc?: string;
  group: string;
  type: SettingType;
  default: boolean | number | string;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  options?: { value: string; label: string }[];
  scope: 'server' | 'client';
  restartRequired?: boolean;
  placeholder?: string;
  danger?: boolean;
}

export const SETTINGS_SCHEMA: SettingDef[] = [
  {
    key: 'AIGENT_PROVIDER',
    label: 'Provider',
    desc: 'LLM provider. Auto-detected from available API keys if omitted.',
    group: 'Provider',
    type: 'select',
    default: '',
    options: [
      { value: '', label: 'Auto-detect' },
      { value: 'anthropic', label: 'Anthropic' },
      { value: 'openai', label: 'OpenAI / compatible' },
    ],
    scope: 'client',
  },
  {
    key: 'ANTHROPIC_API_KEY',
    label: 'Anthropic API key',
    desc: 'sk-ant-... — stored in .env, never in settings.json.',
    group: 'Provider',
    type: 'password',
    default: '',
    placeholder: 'sk-ant-...',
    scope: 'server',
  },
  {
    key: 'AIGENT_BASE_URL',
    label: 'OpenAI base URL',
    desc: 'Base URL for OpenAI-compatible endpoint (e.g. http://127.0.0.1:1234/v1).',
    group: 'Provider',
    type: 'text',
    default: '',
    placeholder: 'http://127.0.0.1:1234/v1',
    scope: 'client',
  },
  {
    key: 'OPENAI_API_KEY',
    label: 'OpenAI API key',
    desc: 'Used when provider is OpenAI. Stored in .env, never in settings.json.',
    group: 'Provider',
    type: 'password',
    default: '',
    placeholder: 'sk-... or not-needed',
    scope: 'server',
  },
  {
    key: 'AIGENT_MODEL',
    label: 'Default model',
    desc: 'Model used at startup. Can be changed live from the sidebar.',
    group: 'Model',
    type: 'model-picker',
    default: '',
    placeholder: 'e.g. claude-opus-4-6 or google/gemini-2.0-flash',
    scope: 'client',
  },
  {
    key: 'AIGENT_FLASH_MODEL',
    label: 'Flash model',
    desc: 'Fast, low-cost tier. Used for simple search, summarization, classification. Falls back to Haiku family if unset.',
    group: 'Model',
    type: 'model-picker',
    default: '',
    placeholder: 'e.g. claude-haiku-4-5-20251001',
    scope: 'client',
  },
  {
    key: 'AIGENT_PRO_MODEL',
    label: 'Pro model',
    desc: 'Balanced tier. Used for analysis, code changes, moderate reasoning. Falls back to Sonnet family if unset.',
    group: 'Model',
    type: 'model-picker',
    default: '',
    placeholder: 'e.g. claude-sonnet-4-6',
    scope: 'client',
  },
  {
    key: 'AIGENT_ULTRA_MODEL',
    label: 'Ultra model',
    desc: 'Most capable tier. Used for complex reasoning and architecture. Falls back to Opus family if unset.',
    group: 'Model',
    type: 'model-picker',
    default: '',
    placeholder: 'e.g. claude-opus-4-6',
    scope: 'client',
  },
  {
    key: 'AIGENT_THINKING',
    label: 'Default reasoning level',
    desc: 'Reasoning level at startup: off, low, medium, high, or max.',
    group: 'Model',
    type: 'select',
    default: 'high',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'low', label: 'Low' },
      { value: 'medium', label: 'Medium' },
      { value: 'high', label: 'High' },
      { value: 'max', label: 'Max' },
    ],
    scope: 'client',
  },
  {
    key: 'AIGENT_SHORT',
    label: 'Speak: short',
    desc: 'Start with Speak set to "short" at startup (auto-speak + concise responses).',
    group: 'Model',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'model_max_tokens',
    label: 'Per-model max tokens',
    desc: 'Max tokens for each model tier. Set individually for Flash, Pro, and Ultra models. Leave blank to use default (16384).',
    group: 'Model',
    type: 'model-tokens',
    default: '{}',
    scope: 'client',
  },
  // ── Fine-tuned model parameters ─────────────────────────────────────────
  {
    key: 'model_temperature',
    label: 'Default temperature',
    desc: 'Controls randomness in responses (0.0 = deterministic, 1.0 = creative). Range: 0.0 to 2.0. Recommended: 0.7 for most tasks.',
    group: 'Model',
    type: 'number',
    default: 0.7,
    min: 0.0,
    max: 2.0,
    step: 0.1,
    scope: 'client',
  },
  {
    key: 'model_top_p',
    label: 'Top P (nucleus sampling)',
    desc: 'Cumulative probability for nucleus sampling (0.0 to 1.0). Lower values = more focused. Recommended: 0.9-0.95.',
    group: 'Model',
    type: 'number',
    default: 0.95,
    min: 0.0,
    max: 1.0,
    step: 0.01,
    scope: 'client',
  },
  {
    key: 'model_top_k',
    label: 'Top K (sampling from top K tokens)',
    desc: 'Limit sampling to top K tokens per token (0 = disabled). Recommended: 40-80 for focused generation.',
    group: 'Model',
    type: 'number',
    default: 0,
    min: 0,
    max: 500,
    step: 1,
    unit: ' tokens',
    scope: 'client',
  },
  {
    key: 'model_presence_penalty',
    label: 'Presence penalty',
    desc: 'Discourages repeating topics (-2.0 to 2.0). Positive = topics discouraged, Negative = topics encouraged. Recommended: 0.0-0.5.',
    group: 'Model',
    type: 'number',
    default: 0.0,
    min: -2.0,
    max: 2.0,
    step: 0.1,
    scope: 'client',
  },
  {
    key: 'model_frequency_penalty',
    label: 'Frequency penalty',
    desc: 'Discourages repeating tokens (-2.0 to 2.0). Positive = repeated tokens discouraged, Negative = encouraged. Recommended: 0.0-0.5.',
    group: 'Model',
    type: 'number',
    default: 0.0,
    min: -2.0,
    max: 2.0,
    step: 0.1,
    scope: 'client',
  },
  {
    key: 'model_repetition_penalty',
    label: 'Repetition penalty',
    desc: 'Penalty for repeated tokens (0.5 to 2.0). >1.0 reduces repetition, <1.0 encourages repetition. Recommended: 1.1.',
    group: 'Model',
    type: 'number',
    default: 1.1,
    min: 0.5,
    max: 2.0,
    step: 0.05,
    scope: 'client',
  },
  {
    key: 'model_stop_sequences',
    label: 'Stop sequences',
    desc: 'Comma-separated sequences that stop generation. One per line. Example: "###", "Human:", "Q:". Leave blank to use defaults.',
    group: 'Model',
    type: 'text',
    default: '',
    placeholder: '###\nHuman:\nQ:',
    scope: 'client',
  },
  {
    key: 'model_allow_parallel_tool_use',
    label: 'Allow parallel tool use',
    desc: 'Enable when the model supports calling multiple tools in a single turn.',
    group: 'Model',
    type: 'toggle',
    default: true,
    scope: 'client',
  },
  {
    key: 'model_use_system_prompt_caching',
    label: 'Use system prompt caching',
    desc: 'Enable prompt caching for system messages (reduces cost for repeated prompts). Only works with supported providers.',
    group: 'Model',
    type: 'toggle',
    default: true,
    scope: 'client',
  },
  {
    key: 'model_use_response_caching',
    label: 'Use response caching',
    desc: 'Enable response caching for identical requests (reduces cost for repeated queries). Only works with Anthropic.',
    group: 'Model',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'model_max_tool_calls',
    label: 'Max tool calls per turn',
    desc: 'Maximum number of tool calls allowed in a single turn. 0 = unlimited. Recommended: 10-20 for complex tasks.',
    group: 'Model',
    type: 'number',
    default: 0,
    min: 0,
    max: 100,
    step: 1,
    unit: ' calls',
    scope: 'client',
  },
  {
    key: 'model_image_input_quality',
    label: 'Image input quality',
    desc: 'Image compression quality for vision models. "low" = cheaper/faster, "high" = better quality.',
    group: 'Model',
    type: 'select',
    default: 'high',
    options: [
      { value: 'low', label: 'Low (cheaper, faster)' },
      { value: 'high', label: 'High (better quality)' },
    ],
    scope: 'client',
  },
  {
    key: 'model_image_input_max_images',
    label: 'Max images per message',
    desc: 'Maximum number of images allowed in a single user message. 0 = unlimited.',
    group: 'Model',
    type: 'number',
    default: 5,
    min: 0,
    max: 20,
    step: 1,
    unit: ' images',
    scope: 'client',
  },
  {
    key: 'model_document_input_max_pages',
    label: 'Max PDF pages per message',
    desc: 'Maximum number of PDF pages to process in a single message. 0 = process all pages.',
    group: 'Model',
    type: 'number',
    default: 20,
    min: 0,
    max: 1000,
    step: 10,
    unit: ' pages',
    scope: 'client',
  },
  // ── Advanced streaming & safety ──────────────────────────────────────────
  {
    key: 'AIGENT_STREAM_TIMEOUT',
    label: 'Stream timeout (ms)',
    desc: 'Maximum time to wait for a stream to complete before aborting. Default: 120000 (120s).',
    group: 'Advanced',
    type: 'number',
    default: 120000,
    min: 1000,
    max: 600000,
    step: 1000,
    unit: ' ms',
    scope: 'server',
  },
  {
    key: 'AIGENT_MAX_REASONING_TOKENS',
    label: 'Max reasoning tokens',
    desc: 'Maximum reasoning tokens before aborting (50% of maxTokens by default). Prevents infinite thinking loops.',
    group: 'Advanced',
    type: 'number',
    default: 8192,
    min: 100,
    max: 32768,
    step: 100,
    unit: ' tokens',
    scope: 'server',
  },
  {
    key: 'model_per_model_config',
    label: 'Per-model fine-tuned parameters',
    desc: 'Fine-tuned parameters for each model tier. JSON object mapping model IDs to their custom settings. Example: {"claude-opus-4-6": {"temperature": 0.3, "max_tokens": 32000}, "claude-haiku-4-5": {"temperature": 0.7, "max_tokens": 8192}}. Leave blank for defaults.',
    group: 'Model',
    type: 'text',
    default: '{}',
    placeholder: '{"model-name": {"temperature": 0.7, "max_tokens": 16384}}',
    scope: 'client',
  },
  {
    key: 'AIGENT_MULTILINE_ENTER',
    label: 'Multiline Enter',
    desc: 'Enter inserts newline, Ctrl+Enter sends. Shift+Enter toggles reasoning.',
    group: 'Input',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'wake_lock',
    type: 'toggle',
    label: 'Keep awake while working',
    desc: 'Prevent computer from sleeping while the agent is working (screen may still dim)',
    group: 'Input',
    scope: 'client',
    default: false,
  },
  // ── Notifications ──────────────────────────────────────────────────────────
  {
    key: 'notify_sound_permission',
    label: 'Sound on permission request',
    desc: 'Play a chime when the agent needs your approval (command, fetch, file, etc.).',
    group: 'Notifications',
    type: 'toggle',
    default: true,
    scope: 'client',
  },
  {
    key: 'notify_sound_response',
    label: 'Sound on response complete',
    desc: 'Play a tone when the agent finishes responding.',
    group: 'Notifications',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'notify_browser_permission',
    label: 'Browser notification on permission',
    desc: 'Show a desktop notification when the agent needs approval (only when tab is in background).',
    group: 'Notifications',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'notify_browser_response',
    label: 'Browser notification on response',
    desc: 'Show a desktop notification when the agent finishes (only when tab is in background).',
    group: 'Notifications',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'auto_pip',
    label: 'Auto-float on tab switch',
    desc: 'Prompt to enter Picture-in-Picture before the agent switches browser tabs.',
    group: 'Appearance',
    type: 'toggle',
    default: true,
    scope: 'client',
  },
  {
    key: 'AIGENT_THEME',
    label: 'Background theme',
    desc: 'Visual background animation style.',
    group: 'Appearance',
    type: 'select',
    default: 'aurora',
    options: [
      { value: 'aurora', label: 'Aurora (fluid blobs)' },
      { value: 'spectrum', label: 'Spectrum (frequency bars)' },
      { value: 'oscilloscope', label: 'Oscilloscope (waveform)' },
      { value: 'circular', label: 'Circular (radial spectrum)' },
      { value: 'milkdrop', label: 'Milkdrop (psychedelic)' },
      { value: 'circuit', label: 'Circuit (hex network)' },
      { value: 'matrix', label: 'Matrix (digital rain)' },
      { value: 'constellation', label: 'Constellation (starfield)' },
      { value: 'topology', label: 'Topology (contour lines)' },
      { value: 'ember', label: 'Ember (rising particles)' },
      { value: 'fireflies', label: 'Fireflies (drifting glows)' },
      { value: 'rain', label: 'Rain (falling drops)' },
      { value: 'neongrid', label: 'Neon Grid (synthwave)' },
      { value: 'lavalamp', label: 'Lava Lamp (metaball blobs)' },
      { value: 'pcb', label: 'PCB (circuit board)' },
      { value: 'neuron', label: 'Neuron (neural network)' },
      { value: 'chroma', label: 'Chroma (colour wash)' },
    ],
    scope: 'client',
  },
  {
    key: 'AIGENT_THEME_ROTATE_MINS',
    label: 'Theme rotation interval',
    desc: 'Smoothly rotate through all themes every N minutes. 0 disables rotation.',
    group: 'Appearance',
    type: 'number',
    default: 0,
    min: 0,
    max: 60,
    step: 1,
    unit: ' min',
    scope: 'client',
  },
  {
    key: 'AIGENT_NO_TOOLS',
    label: 'Disable all tools',
    desc: 'Send no tool definitions to the model.',
    group: 'Tools',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'AIGENT_TOOLS_ALLOWLIST',
    label: 'Tool allowlist',
    desc: 'Comma-separated list of tools to enable. Leave blank to enable all.',
    group: 'Tools',
    type: 'text',
    default: '',
    placeholder: 'exec,read_file,write_file',
    scope: 'client',
  },
  {
    key: 'AIGENT_SLIM_PROMPT',
    label: 'Slim prompt',
    desc: 'Omit MEMORY.md from the system prompt to save tokens.',
    group: 'Prompt',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'AIGENT_FULL_LOGS',
    label: 'Full session logs in prompt',
    desc: 'Include complete recent session logs in the system prompt.',
    group: 'Prompt',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'AIGENT_WEB_PORT',
    label: 'Web UI port',
    desc: 'Port the web server listens on.',
    group: 'Services',
    type: 'number',
    default: 3141,
    min: 1024,
    max: 65535,
    scope: 'client',
  },
  {
    key: 'AIGENT_STT_URL',
    label: 'STT service URL',
    desc: 'Speech-to-text service endpoint.',
    group: 'Services',
    type: 'text',
    default: 'http://127.0.0.1:8765',
    placeholder: 'http://127.0.0.1:8765',
    scope: 'client',
  },
  {
    key: 'AIGENT_TTS_URL',
    label: 'TTS service URL',
    desc: 'Text-to-speech service endpoint.',
    group: 'Services',
    type: 'text',
    default: 'http://127.0.0.1:8766',
    placeholder: 'http://127.0.0.1:8766',
    scope: 'client',
  },
  {
    key: 'mic_silence_threshold',
    label: 'Silence threshold',
    desc: 'Controls the visual mic pulse and auto-send timing only — does not affect what gets transcribed. Audio is always sent to the STT service regardless of this value.',
    group: 'Microphone',
    type: 'number',
    default: 0.015,
    min: 0.001,
    max: 0.2,
    step: 0.001,
    scope: 'client',
  },
  {
    key: 'mic_loud_frames',
    label: 'Speech onset frames',
    desc: 'Controls the visual mic pulse only — does not affect what gets transcribed. Sets how many consecutive loud frames are needed before the pulse activates.',
    group: 'Microphone',
    type: 'number',
    default: 2,
    min: 1,
    max: 10,
    step: 1,
    unit: ' frames',
    scope: 'client',
  },
  {
    key: 'mic_silence_tail_ms',
    label: 'Silence tail',
    desc: 'How long to keep accumulating audio after speech ends.',
    group: 'Microphone',
    type: 'number',
    default: 500,
    min: 100,
    max: 2000,
    step: 50,
    unit: ' ms',
    scope: 'client',
  },
  {
    key: 'stt_energy_threshold',
    label: 'STT energy threshold',
    desc: 'Minimum RMS volume required before audio is sent to the speech-to-text model. Audio quieter than this is discarded without transcription, preventing Parakeet from hallucinating words from silence or background noise. Raise this if you get spurious words when not speaking. 0 disables the gate entirely.',
    group: 'Microphone',
    type: 'number',
    default: 0.01,
    min: 0,
    max: 0.1,
    step: 0.001,
    scope: 'client',
  },
  {
    key: 'mic_auto_send',
    label: 'Auto-send on silence',
    desc: 'In always-on mode: automatically submit after silence is detected.',
    group: 'Microphone',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'mic_auto_send_ms',
    label: 'Auto-send silence duration',
    desc: 'How long silence must persist before auto-sending.',
    group: 'Microphone',
    type: 'number',
    default: 1500,
    min: 300,
    max: 5000,
    step: 100,
    unit: ' ms',
    scope: 'client',
  },
  {
    key: 'mic_idle_timeout_min',
    label: 'Idle timeout',
    desc: 'In always-on mode: automatically stop microphone after this many minutes of silence. 0 = never.',
    group: 'Microphone',
    type: 'number',
    default: 2,
    min: 0,
    max: 10,
    step: 1,
    unit: ' min',
    scope: 'client',
  },
  {
    key: 'tools_summarizeLargeResults',
    label: 'Summarize large results',
    desc: 'Summarize tool outputs that exceed the token threshold.',
    group: 'Context',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'tools_summarizeThresholdTokens',
    label: 'Summarize threshold',
    desc: 'Tool outputs larger than this (in tokens) will be summarized.',
    group: 'Context',
    type: 'number',
    default: 500,
    min: 100,
    max: 10000,
    step: 100,
    unit: ' tok',
    scope: 'client',
  },
  {
    key: 'tools_summarizeModel',
    label: 'Summarize model',
    desc: 'Model used for summarization.',
    group: 'Context',
    type: 'text',
    default: '',
    placeholder: 'e.g. claude-haiku-4-5-20251001 or google/gemini-flash-lite',
    scope: 'client',
  },
  {
    key: 'tools_summarizeMode',
    label: 'Tool filter mode',
    desc: 'allowlist: only summarize checked tools. blocklist: all except checked. all: every tool.',
    group: 'Context',
    type: 'select',
    default: 'allowlist',
    options: [
      { value: 'allowlist', label: 'Allowlist (only checked)' },
      { value: 'blocklist', label: 'Blocklist (all except checked)' },
      { value: 'all', label: 'All tools' },
    ],
    scope: 'client',
  },
  {
    key: 'exec_perm_yolo',
    label: 'YOLO mode',
    desc: 'Auto-approve ALL commands. Tier 1 hard deny (shell injection, credential access, privilege escalation) is still enforced.',
    group: 'Permissions',
    type: 'toggle',
    default: false,
    scope: 'client',
    danger: true,
  },
  {
    key: 'exec_perm_alwaysAllow',
    label: 'Always Allow',
    desc: 'One pattern per line. "ls" = ls and ls <args>. "git *" = any git subcommand. "*" = allow all. "?" = single char.',
    group: 'Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'exec_perm_alwaysClassify',
    label: 'Always Classify',
    desc: 'Commands matching these patterns are always sent to the Haiku classifier, even if they match an Allow pattern. One pattern per line.',
    group: 'Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'exec_perm_deny',
    label: 'Always Deny',
    desc: 'One pattern per line. Same syntax as Allow. Deny rules always win over Allow.',
    group: 'Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'fetch_perm_yolo',
    label: 'YOLO mode',
    desc: 'Auto-approve ALL fetch requests. SSRF protection (private IPs, metadata endpoints) is still enforced.',
    group: 'Fetch Permissions',
    type: 'toggle',
    default: false,
    scope: 'client',
    danger: true,
  },
  {
    key: 'fetch_perm_alwaysAllow',
    label: 'Always Allow',
    desc: 'One pattern per line. "example.com" = hostname. "*.example.com" = subdomains. "https://api.example.com/v1/*" = URL prefix. "*" = allow all.',
    group: 'Fetch Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'fetch_perm_deny',
    label: 'Always Deny',
    desc: 'One pattern per line. Same syntax as Allow. Deny rules always win over Allow.',
    group: 'Fetch Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'file_perm_yolo',
    label: 'YOLO mode',
    desc: 'Auto-approve ALL file read/write requests. Hard-deny paths (~/.ssh, ~/.gnupg, ~/.aws, /proc, /sys) are still enforced.',
    group: 'File Permissions',
    type: 'toggle',
    default: false,
    scope: 'client',
    danger: true,
  },
  {
    key: 'file_perm_readWrite',
    label: 'Read-Write',
    desc: 'Paths where the agent can both read and write. One pattern per line. "~/project/**" = all files under project. "/tmp/*" = files in /tmp. "*" = allow all. ~ expands to your home directory.',
    group: 'File Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'file_perm_readOnly',
    label: 'Read-Only',
    desc: 'Paths where the agent can read but not write. Writes are automatically denied. Same pattern syntax as Read-Write.',
    group: 'File Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'file_perm_deny',
    label: 'Deny',
    desc: 'Paths blocked for both reading and writing. Deny rules always win. Defaults include ~/.ssh, ~/.gnupg, ~/.aws.',
    group: 'File Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'browser_perm_read',
    label: 'Read',
    desc: 'Domains where the agent can read the page (a11y tree, screenshots). One per line. "github.com", "*.google.com".',
    group: 'Browser Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'browser_perm_write',
    label: 'Write',
    desc: 'Domains where the agent can click, fill forms, navigate. Implies read. One per line.',
    group: 'Browser Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'browser_perm_script',
    label: 'Script',
    desc: 'Domains where the agent can execute arbitrary JavaScript. Implies write + read. One per line.',
    group: 'Browser Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'browser_perm_deny',
    label: 'Deny',
    desc: 'Domains blocked from all browser automation. Deny rules always win.',
    group: 'Browser Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'mcp_perm_servers',
    label: 'Server permissions',
    desc: 'JSON mapping server names to permission config. Example: {"github": {"default": "allow", "tools": {"delete_repo": "deny"}}}. Levels: "allow", "deny", "prompt" (default).',
    group: 'MCP Permissions',
    type: 'text',
    default: '{}',
    scope: 'client',
  },
  // ── Keybindings ────────────────────────────────────────────────────────────
  {
    key: 'keybind_toggleMic',
    label: 'Toggle microphone',
    desc: 'Comma-separated list of chords (e.g. "Ctrl+Backtick, Backtick, M"). Backtick/M without modifiers only fire when no text input is focused.',
    group: 'Keybindings',
    type: 'text',
    default: 'Ctrl+Backtick, Backtick, M',
    placeholder: 'Ctrl+Backtick, Backtick, M',
    scope: 'client',
  },
  {
    key: 'keybind_toggleMicSticky',
    label: 'Toggle sticky mic (always-on)',
    desc: 'Comma-separated list of chords.',
    group: 'Keybindings',
    type: 'text',
    default: 'Ctrl+Shift+Backtick',
    placeholder: 'Ctrl+Shift+Backtick',
    scope: 'client',
  },
  {
    key: 'keybind_cancelResponse',
    label: 'Cancel response',
    desc: 'Chord to stop an in-progress agent response. Supports hold: prefix for long-press (e.g. hold:Escape = hold Escape for 1s, hold:500:Escape = hold for 500ms, Ctrl+Escape = immediate chord).',
    group: 'Keybindings',
    type: 'text',
    default: 'hold:Escape',
    placeholder: 'hold:Escape',
    scope: 'client',
  },
  {
    key: 'keybind_clearInput',
    label: 'Clear input box',
    desc: 'Comma-separated list of chords.',
    group: 'Keybindings',
    type: 'text',
    default: 'Escape',
    placeholder: 'Escape',
    scope: 'client',
  },
  {
    key: 'keybind_showShortcuts',
    label: 'Show keyboard shortcuts',
    desc: 'Comma-separated list of chords.',
    group: 'Keybindings',
    type: 'text',
    default: 'Ctrl+?, Ctrl+Shift+/',
    placeholder: 'Ctrl+?, Ctrl+Shift+/',
    scope: 'client',
  },
  {
    key: 'debug_browser_errors',
    label: 'Relay browser errors to server',
    desc: 'Capture console.warn/error, uncaught exceptions and unhandled rejections — send them to the server log and show in chat.',
    group: 'Debug',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
];
