export interface CommandDef {
  name: string;
  desc: string;
  argHint?: string;
}

export const COMMANDS: CommandDef[] = [
  { name: '/help',      desc: 'Show available commands' },
  { name: '/reset',     desc: 'Clear conversation' },
  { name: '/compact',   desc: 'Compact context' },
  { name: '/refresh',   desc: 'Reload workspace files' },
  { name: '/restart',   desc: 'Restart server' },
  { name: '/reasoning', desc: 'Toggle reasoning',          argHint: 'on|off' },
  { name: '/effort',    desc: 'Set effort level',          argHint: 'low|medium|high|max' },
  { name: '/short',     desc: 'Short/voice mode',            argHint: 'on|off' },
  { name: '/model',     desc: 'Show or switch model',      argHint: '<name>' },
  { name: '/image',     desc: 'Send an image',             argHint: '<path> [msg]' },
  { name: '/usage',     desc: 'Token usage stats' },
  { name: '/context',   desc: 'Context window breakdown' },
  { name: '/tasks',     desc: 'Background tasks' },
  { name: '/profiles',  desc: 'List profiles' },
  { name: '/profile',   desc: 'Switch profile',            argHint: '<name>' },
  { name: '/save',      desc: 'Save session' },
  { name: '/sessions',  desc: 'List sessions' },
  { name: '/load',      desc: 'Load session',              argHint: '<id>' },
  { name: '/grant',     desc: 'Approve pending request' },
  { name: '/deny',      desc: 'Deny pending request' },
  { name: '/approve',        desc: 'Approve config write' },
  { name: '/reject',         desc: 'Reject config write' },
  { name: '/preview',        desc: 'Preview config write' },
  { name: '/approve-patch',  desc: 'Approve patch request' },
  { name: '/reject-patch',   desc: 'Reject patch request' },
];

export type SettingType = 'toggle' | 'slider' | 'number' | 'text' | 'select' | 'password' | 'string-list';

export interface SettingDef {
  key: string;
  label: string;
  desc?: string;
  group: string;
  type: SettingType;
  default: boolean | number | string;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  options?: { value: string; label: string }[];
  scope: 'server' | 'client';
  restartRequired?: boolean;
  placeholder?: string;
}

export const SETTINGS_SCHEMA: SettingDef[] = [
  {
    key: 'AIGENT_PROVIDER',
    label: 'Provider',
    desc: 'LLM provider. Auto-detected from available API keys if omitted.',
    group: 'Provider',
    type: 'select',
    default: '',
    options: [
      { value: '', label: 'Auto-detect' },
      { value: 'anthropic', label: 'Anthropic' },
      { value: 'openai', label: 'OpenAI / compatible' },
    ],
    scope: 'client',
  },
  {
    key: 'ANTHROPIC_API_KEY',
    label: 'Anthropic API key',
    desc: 'sk-ant-... — stored in .env, never in settings.json.',
    group: 'Provider',
    type: 'password',
    default: '',
    placeholder: 'sk-ant-...',
    scope: 'server',
  },
  {
    key: 'AIGENT_BASE_URL',
    label: 'OpenAI base URL',
    desc: 'Base URL for OpenAI-compatible endpoint (e.g. http://127.0.0.1:1234/v1).',
    group: 'Provider',
    type: 'text',
    default: '',
    placeholder: 'http://127.0.0.1:1234/v1',
    scope: 'client',
  },
  {
    key: 'OPENAI_API_KEY',
    label: 'OpenAI API key',
    desc: 'Used when provider is OpenAI. Stored in .env, never in settings.json.',
    group: 'Provider',
    type: 'password',
    default: '',
    placeholder: 'sk-... or not-needed',
    scope: 'server',
  },
  {
    key: 'AIGENT_MODEL',
    label: 'Default model',
    desc: 'Model used at startup. Can be changed live from the sidebar.',
    group: 'Model',
    type: 'text',
    default: 'claude-opus-4-6',
    placeholder: 'claude-opus-4-6',
    scope: 'client',
  },
  {
    key: 'AIGENT_THINKING',
    label: 'Default reasoning level',
    desc: 'Reasoning level at startup: off, low, medium, high, or max.',
    group: 'Model',
    type: 'select',
    default: 'high',
    options: [
      { value: 'off', label: 'Off' },
      { value: 'low', label: 'Low' },
      { value: 'medium', label: 'Medium' },
      { value: 'high', label: 'High' },
      { value: 'max', label: 'Max' },
    ],
    scope: 'client',
  },
  {
    key: 'AIGENT_SHORT',
    label: 'Short mode',
    desc: 'Start in short/voice mode at startup.',
    group: 'Model',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'AIGENT_THEME',
    label: 'Background theme',
    desc: 'Visual background animation style.',
    group: 'Appearance',
    type: 'select',
    default: 'aurora',
    options: [
      { value: 'aurora', label: 'Aurora (fluid blobs)' },
      { value: 'spectrum', label: 'Spectrum (frequency bars)' },
      { value: 'oscilloscope', label: 'Oscilloscope (waveform)' },
      { value: 'circular', label: 'Circular (radial spectrum)' },
      { value: 'milkdrop', label: 'Milkdrop (psychedelic)' },
      { value: 'circuit', label: 'Circuit (hex network)' },
      { value: 'matrix', label: 'Matrix (digital rain)' },
      { value: 'constellation', label: 'Constellation (starfield)' },
      { value: 'topology', label: 'Topology (contour lines)' },
      { value: 'ember', label: 'Ember (rising particles)' },
    ],
    scope: 'client',
  },
  {
    key: 'AIGENT_NO_TOOLS',
    label: 'Disable all tools',
    desc: 'Send no tool definitions to the model.',
    group: 'Tools',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'AIGENT_TOOLS_ALLOWLIST',
    label: 'Tool allowlist',
    desc: 'Comma-separated list of tools to enable. Leave blank to enable all.',
    group: 'Tools',
    type: 'text',
    default: '',
    placeholder: 'exec,read_file,write_file',
    scope: 'client',
  },
  {
    key: 'AIGENT_SLIM_PROMPT',
    label: 'Slim prompt',
    desc: 'Omit MEMORY.md from the system prompt to save tokens.',
    group: 'Prompt',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'AIGENT_FULL_LOGS',
    label: 'Full session logs in prompt',
    desc: 'Include complete recent session logs in the system prompt.',
    group: 'Prompt',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'AIGENT_WEB_PORT',
    label: 'Web UI port',
    desc: 'Port the web server listens on.',
    group: 'Services',
    type: 'number',
    default: 3141,
    min: 1024,
    max: 65535,
    scope: 'client',
  },
  {
    key: 'AIGENT_STT_URL',
    label: 'STT service URL',
    desc: 'Speech-to-text service endpoint.',
    group: 'Services',
    type: 'text',
    default: 'http://127.0.0.1:8765',
    placeholder: 'http://127.0.0.1:8765',
    scope: 'client',
  },
  {
    key: 'AIGENT_TTS_URL',
    label: 'TTS service URL',
    desc: 'Text-to-speech service endpoint.',
    group: 'Services',
    type: 'text',
    default: 'http://127.0.0.1:8766',
    placeholder: 'http://127.0.0.1:8766',
    scope: 'client',
  },
  {
    key: 'mic_silence_threshold',
    label: 'Silence threshold',
    desc: 'RMS level below which audio is treated as silence.',
    group: 'Microphone',
    type: 'number',
    default: 0.015,
    min: 0.001,
    max: 0.2,
    step: 0.001,
    scope: 'client',
  },
  {
    key: 'mic_loud_frames',
    label: 'Speech onset frames',
    desc: 'Consecutive loud frames required before speech is considered active.',
    group: 'Microphone',
    type: 'number',
    default: 2,
    min: 1,
    max: 10,
    step: 1,
    unit: ' frames',
    scope: 'client',
  },
  {
    key: 'mic_silence_tail_ms',
    label: 'Silence tail',
    desc: 'How long to keep accumulating audio after speech ends.',
    group: 'Microphone',
    type: 'number',
    default: 500,
    min: 100,
    max: 2000,
    step: 50,
    unit: ' ms',
    scope: 'client',
  },
  {
    key: 'mic_auto_send',
    label: 'Auto-send on silence',
    desc: 'In always-on mode: automatically submit after silence is detected.',
    group: 'Microphone',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'mic_auto_send_ms',
    label: 'Auto-send silence duration',
    desc: 'How long silence must persist before auto-sending.',
    group: 'Microphone',
    type: 'number',
    default: 1500,
    min: 300,
    max: 5000,
    step: 100,
    unit: ' ms',
    scope: 'client',
  },
  {
    key: 'tools_summarizeLargeResults',
    label: 'Summarize large results',
    desc: 'Summarize tool outputs that exceed the token threshold.',
    group: 'Context',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
  {
    key: 'tools_summarizeThresholdTokens',
    label: 'Summarize threshold',
    desc: 'Tool outputs larger than this (in tokens) will be summarized.',
    group: 'Context',
    type: 'number',
    default: 500,
    min: 100,
    max: 10000,
    step: 100,
    unit: ' tok',
    scope: 'client',
  },
  {
    key: 'tools_summarizeModel',
    label: 'Summarize model',
    desc: 'Model used for summarization.',
    group: 'Context',
    type: 'text',
    default: 'claude-haiku-4-5-20251001',
    placeholder: 'claude-haiku-4-5-20251001',
    scope: 'client',
  },
  {
    key: 'tools_summarizeMode',
    label: 'Tool filter mode',
    desc: 'allowlist: only summarize checked tools. blocklist: all except checked. all: every tool.',
    group: 'Context',
    type: 'select',
    default: 'allowlist',
    options: [
      { value: 'allowlist', label: 'Allowlist (only checked)' },
      { value: 'blocklist', label: 'Blocklist (all except checked)' },
      { value: 'all', label: 'All tools' },
    ],
    scope: 'client',
  },
  {
    key: 'exec_perm_alwaysAllow',
    label: 'Always Allow',
    desc: 'One pattern per line. "ls" = ls and ls <args>. "git *" = any git subcommand. "*" = allow all. "?" = single char.',
    group: 'Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'exec_perm_deny',
    label: 'Always Deny',
    desc: 'One pattern per line. Same syntax as Allow. Deny rules always win over Allow.',
    group: 'Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'fetch_perm_alwaysAllow',
    label: 'Always Allow',
    desc: 'One pattern per line. "example.com" = hostname. "*.example.com" = subdomains. "https://api.example.com/v1/*" = URL prefix. "*" = allow all.',
    group: 'Fetch Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'fetch_perm_deny',
    label: 'Always Deny',
    desc: 'One pattern per line. Same syntax as Allow. Deny rules always win over Allow.',
    group: 'Fetch Permissions',
    type: 'string-list',
    default: '[]',
    scope: 'client',
  },
  {
    key: 'debug_browser_errors',
    label: 'Relay browser errors to server',
    desc: 'Capture console.warn/error, uncaught exceptions and unhandled rejections — send them to the server log and show in chat.',
    group: 'Debug',
    type: 'toggle',
    default: false,
    scope: 'client',
  },
];
